### ISSUE TITLE
virtualization

### ISSUE THREAD

**Issue by yeasin-hossain** [snelsi/react-awesome-ticker#62]
**Is your feature request related to a problem? Please describe.**
I'm not able to render lot of data 

**Describe the solution you'd like**
you should use react-window

**Describe alternatives you've considered**

**Additional context**

**Comment by snelsi** [comment]
This library uses native css animations to achieve a simple 'running' ticker effect. 
Adding virtualization would require some heavy JS logic and will probably pull a complete rewrite of the library.

Sorry, I don't think that it's reasonable to implement this right now.

If you need virtualization, consider migrating to something like [react-ticker](https://andreasfaust.github.io/react-ticker/) or its alternatives.
